from .ackley import ackley
from .alpine import alpine
from .chung_reynolds import chung_reynolds
from .cosine_mixture import cosine_mixture
from .dixon_price import dixon_price
from .griewank import griewank
from .pinter import pinter
from .powel import powel
from .qing import qing
from .schaffer import expanded_schaffer